fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format-code-black
        name: Format with black
        pass_filenames: false
        language: system
        entry: bash -c 'black . --check'
      - id: format-code-isort
        name: Format with isort
        pass_filenames: false
        language: system
        entry: bash -c 'isort . --check'
      - id: lint-code
        name: Lint
        pass_filenames: false
        language: system
        entry: bash -c 'mypy resize tests --disallow-untyped-defs && pylint resize && pylint tests'
      - id: test-code
        name: Test
        pass_filenames: false
        language: system
        entry: bash -c 'pytest -s'